### ISSUE TITLE
functions is.parent() and parent.study() 

### ISSUE THREAD

**Issue by gversmee** [gversmee/dbgap2x#8]
On the Jupyter/mybinder, http request error.
`Error in curl::curl_fetch_memory(url, handle = handle): Error in the HTTP2 framing layer Tracebak`

**Comment by mikaeldusenne** [comment]
surprising thing: it actually works intermittently....

**Comment by mikaeldusenne** [comment]
update: the phs.version function seemed to be causing issues, but not the GET request in is.parent().

running  `httr::set_config(httr::config(http_version = RCurl::HTTP_VERSION_1_1))` before performing the requests solves the issue (from https://github.com/jeroen/curl/issues/156 )
(the default seems to be RCurl::HTTP_VERSION_LAST )

it does not seem to impact negatively the request time, maybe we should perform some tests.
